services:
  frontend:
    image: frontend:1.0
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./frontend/tools/certs:/etc/ssl/certs
    networks:
      - transcendence
  api:
    image: transcendence-api:1.0
    container_name: transcendence_api
    depends_on:
      - postgres
    build:
      context: ./backend/api
      dockerfile: Dockerfile 
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "3001:3001"
    networks:
      - transcendence

  postgres:
    container_name: brunchio_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-yourUser}
      - POSTGRES_PASSWORD=${POSTGRES_PW:-changeit}
      - POSTGRES_DB=${POSTGRES_DB:-brunchio_db}
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./database/tools/certs/postgres-ssl-certs:/var/lib/postgresql/ssl:ro
    restart: always
    command: |
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt
      -c ssl_key_file=/var/lib/postgresql/ssl/server.key
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/postgresql/ssl/server.crt && test -f /var/lib/postgresql/ssl/server.key && pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    networks:
      - transcendence

  pgadmin:
    container_name: brunchio_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_ENABLE_TLS=true
    ports:
      - "5050:443"
    restart: always
    volumes:
      - ./database/tools/server.json:/pgadmin4/servers.json
      - ./database/tools/certs/pgadmin:/certs
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - transcendence

  postgres_exporter:
    container_name: brunchio_postgres_exporter
    image: prometheuscommunity/postgres-exporter:latest
    env_file:
      - .env
    ports:
      - "9187:9187"
    volumes:
      - ./monitoring/postgres-exporter-web.yml:/etc/postgres_exporter/web.yml:ro
      - ./monitoring/tools/certs/postgres_exporter/postgres_exporter.crt:/etc/postgres_exporter/certs/postgres_exporter.crt:ro
      - ./monitoring/tools/certs/postgres_exporter/postgres_exporter.key:/etc/postgres_exporter/certs/postgres_exporter.key:ro
    depends_on:
      - postgres
    restart: always
    networks:
      - transcendence
    
  prometheus:
    container_name: brunchio_prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus-web.yml:/etc/prometheus/web.yml:ro
      - ./monitoring/tools/certs/prometheus/prometheus.crt:/etc/prometheus/certs/prometheus.crt:ro
      - ./monitoring/tools/certs/prometheus/prometheus.key:/etc/prometheus/certs/prometheus.key:ro
    depends_on:
      - postgres_exporter
    restart: always
    networks:
      - transcendence

  grafana:
    container_name: brunchio_grafana
    image: grafana/grafana:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    - ./monitoring/tools/certs/grafana/grafana.crt:/etc/grafana/certs/grafana.crt:ro
    - ./monitoring/tools/certs/grafana/grafana.key:/etc/grafana/certs/grafana.key:ro
    depends_on:
      - prometheus
    restart: always
    networks:
      - transcendence

volumes:
    postgres_data:
    pgadmin_data:
    grafana_data:

networks:
  transcendence:
    driver: bridge