services:
  frontend:
    image: frontend:1.0
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    restart: always
    ports:
      - "1025:1025"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=1025
      - SSL_CERT_PATH=/etc/ssl/certs/server.crt
      - SSL_KEY_PATH=/etc/ssl/certs/server.key
      - FRONTEND_API_TARGET=https://api:3443
    depends_on:
      - api
    volumes:
      - ./frontend/tools/certs:/etc/ssl/certs:ro
    networks:
      - transcendence
  api:
    image: transcendence-api-gateway:1.0
    container_name: transcendence_api_gateway
    depends_on:
      - auth-service
      - recipes-service
    build:
      context: ./backend/services/api-gateway
      dockerfile: Dockerfile 
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3443
      - AUTH_SERVICE_URL=http://auth-service:3001
      - RECIPES_SERVICE_URL=http://recipes-service:3002
      - PROXY_CONNECT_TIMEOUT_MS=3000
      - PROXY_RESPONSE_TIMEOUT_MS=5000
    ports:
      - "3443:3443"
    volumes:
      - ./frontend/tools/certs:/etc/ssl/certs:ro
    networks:
      - transcendence

  auth-service:
    image: transcendence-auth-service:1.0
    container_name: transcendence_auth_service
    depends_on:
      - postgres
      - redis
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3001
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6378
      - RATE_LIMIT_PER_MINUTE=50
    volumes:
      - uploads_data:/app/uploads
    networks:
      - transcendence

  recipes-service:
    image: transcendence-recipes-service:1.0
    container_name: transcendence_recipes_service
    depends_on:
      - postgres
      - redis
    build:
      context: ./backend/services/recipes-service
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3002
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6378
      - RATE_LIMIT_PER_MINUTE=50
    networks:
      - transcendence

  postgres:
    container_name: brunchio_db
    image: postgres:latest
    entrypoint: ["/docker-entrypoint.sh"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-yourUser}
      - POSTGRES_PASSWORD=${POSTGRES_PW:-changeit}
      - POSTGRES_DB=${POSTGRES_DB:-brunchio_db}
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./database/tools/certs/postgres-ssl-certs:/var/lib/postgresql/ssl
      - ./database/tools/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    restart: always
    command: |
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt
      -c ssl_key_file=/var/lib/postgresql/ssl/server.key
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/postgresql/ssl/server.crt && test -f /var/lib/postgresql/ssl/server.key && pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    networks:
      - transcendence

  pgadmin:
    container_name: brunchio_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_ENABLE_TLS=true
    ports:
      - "5050:443"
    restart: always
    volumes:
      - ./database/tools/server.json:/pgadmin4/servers.json
      - ./database/tools/certs/pgadmin:/certs:ro
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - transcendence

  redis:
    container_name: brunchio_redis
    image: redis:latest
    command: redis-server --port 6378
    ports:
      - "6378:6378"
    restart: always
    networks:
      - transcendence

  postgres_exporter:
    container_name: brunchio_postgres_exporter
    image: prometheuscommunity/postgres-exporter:latest
    env_file:
      - .env
    ports:
      - "9187:9187"
    command:
    - --web.config.file=/etc/postgres_exporter/web.yml
    volumes:
      - ./monitoring/postgres-exporter-web.yml:/etc/postgres_exporter/web.yml:ro
      - ./monitoring/tools/certs/postgres_exporter/postgres_exporter.crt:/etc/postgres_exporter/certs/postgres_exporter.crt:ro
      - ./monitoring/tools/certs/postgres_exporter/postgres_exporter.key:/etc/postgres_exporter/certs/postgres_exporter.key:ro
    depends_on:
      - postgres
    restart: always
    networks:
      - transcendence

  prometheus:
    container_name: brunchio_prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus-web.yml:/etc/prometheus/web.yml:ro
      - ./monitoring/tools/certs/prometheus/prometheus.crt:/etc/prometheus/certs/prometheus.crt:ro
      - ./monitoring/tools/certs/prometheus/prometheus.key:/etc/prometheus/certs/prometheus.key:ro
    depends_on:
      - postgres_exporter
    restart: always
    networks:
      - transcendence

  grafana:
    container_name: brunchio_grafana
    image: grafana/grafana:13.0.1
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    - ./monitoring/tools/certs/grafana/grafana.crt:/etc/grafana/certs/grafana.crt:ro
    - ./monitoring/tools/certs/grafana/grafana.key:/etc/grafana/certs/grafana.key:ro
    depends_on:
      - prometheus
    restart: always
    networks:
      - transcendence

  filebeat:
    container_name: brunchio_filebeat
    build:
      context: ./monitoring/filebeat
      dockerfile: Dockerfile
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    environment:
      - GOINFRE_PATH=/home/${USER}/goinfre
    volumes:
      - /home/$USER/goinfre:/home/$USER/goinfre:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/tools/certs/elk-ca/ca.crt:/usr/share/filebeat/certs/ca.crt:ro
      - filebeat_data:/usr/share/filebeat/data
    depends_on:
      - logstash
    restart: always
    networks:
      - transcendence
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    container_name: brunchio_logstash
    build:
      context: ./monitoring/logstash
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5044:5044"
    volumes:
      - ./monitoring/tools/certs/logstash/logstash.crt:/usr/share/logstash/certs/logstash.crt:ro
      - ./monitoring/tools/certs/logstash/logstash.key:/usr/share/logstash/certs/logstash.key:ro
      - ./monitoring/tools/certs/elk-ca/ca.crt:/usr/share/logstash/certs/ca.crt:ro
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - transcendence
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    container_name: brunchio_elasticsearch
    build:
      context: ./monitoring/elasticsearch
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - discovery.type=${ELASTICSEARCH_DISCOVERY_TYPE:-single-node}
      - xpack.security.enabled=${ELASTICSEARCH_XPACK_SECURITY_ENABLED:-true}
      - xpack.security.http.ssl.enabled=${ELASTICSEARCH_XPACK_SECURITY_HTTP_SSL_ENABLED:-true}
      - xpack.security.http.ssl.certificate=${ELASTICSEARCH_XPACK_SECURITY_HTTP_SSL_CERTIFICATE:-/usr/share/elasticsearch/config/certs/elasticsearch.crt}
      - xpack.security.http.ssl.key=${ELASTICSEARCH_XPACK_SECURITY_HTTP_SSL_KEY:-/usr/share/elasticsearch/config/certs/elasticsearch.key}
      - xpack.security.http.ssl.certificate_authorities=${ELASTICSEARCH_XPACK_SECURITY_HTTP_SSL_CERTIFICATE_AUTHORITIES:-/usr/share/elasticsearch/config/certs/ca.crt}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch.crt
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch.key
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    ports:
      - "9200:9200"
    volumes:
      - ./monitoring/elasticsearch/snapshots:/snapshots
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./monitoring/tools/certs/elasticsearch/elasticsearch.crt:/usr/share/elasticsearch/config/certs/elasticsearch.crt:ro
      - ./monitoring/tools/certs/elasticsearch/elasticsearch.key:/usr/share/elasticsearch/config/certs/elasticsearch.key:ro
      - ./monitoring/tools/certs/elk-ca/ca.crt:/usr/share/elasticsearch/config/certs/ca.crt:ro
    restart: always
    networks:
      - transcendence
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    container_name: brunchio_kibana
    build:
      context: ./monitoring/kibana
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_SSL_ENABLED=${SERVER_SSL_ENABLED}
      - SERVER_SSL_CERTIFICATE=${SERVER_SSL_CERTIFICATE}
      - SERVER_SSL_KEY=${SERVER_SSL_KEY}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}
    ports:
      - "5601:5601"
    volumes:
      - ./monitoring/tools/certs/kibana/kibana.crt:/usr/share/kibana/config/certs/kibana.crt:ro
      - ./monitoring/tools/certs/kibana/kibana.key:/usr/share/kibana/config/certs/kibana.key:ro
      - ./monitoring/tools/certs/elk-ca/ca.crt:/usr/share/kibana/config/certs/ca.crt:ro
      - ./monitoring/kibana/dashboards:/dashboards:ro
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - transcendence
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
    postgres_data:
    pgadmin_data:
    grafana_data:
    filebeat_data:
    elasticsearch_data:
    uploads_data:
      name: transcendence_uploads_data

networks:
  transcendence:
    driver: bridge