services:
  api:
    image: transcendence-api:1.0
    container_name: transcendence_api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
