input {
  beats {
    port => 5044
    ssl_enabled => true
    ssl_certificate => "/usr/share/logstash/certs/logstash.crt"
    ssl_key => "/usr/share/logstash/certs/logstash.key"
  }
}

filter {
  if [container][labels][com_docker_compose_service] not in [
    "api",
    "auth-service",
    "recipes-service",
    "postgres",
    "postgres_exporter",
    "prometheus"
  ] {
    drop {}
  }

  mutate {
    add_field => {
      "service_name" => "%{[container][labels][com_docker_compose_service]}"
      "container_name" => "%{[container][name]}"
    }
  }

  json {
    source => "message"
    target => "app"
    skip_on_invalid_json => true
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
    index => "transcendence-logs-%{+YYYY.MM.dd}"
  }
}