INSERT INTO dev_dba.ingredients (name, price_per_kg, diet_type) VALUES
('Avocado', 5.43, 'Vegan'),
('Pineapple', 1.20, 'Vegan'),
('Acai', 15.60, 'Vegan'),
('Sugar', 1.22, 'Vegan'),
('Brown Sugar', 1.22, 'Vegan'),
('Cumin' ,  27.20, 'Vegan' ),
('Sweet Paprika' ,  19.86, 'Vegan'),
('Powdered Sugar', 2.68, 'Vegan'),
('Agave Syrup', 12.22, 'Vegan'),
('Rosemary', 22.34, 'Vegan'),
('Garlic', 4.00, 'Vegan'),
('Blackberry', 26.00, 'Vegan'),
('Oats', 1.68, 'Vegan'),
('Olive Oil', 31.80, 'Vegan'),
('Herb Olive Oil', 5.03, 'Vegan'),
('Bacon', 6.17, 'Omnivorous'),
('Banana', 1.06, 'Vegan'),
('Beetroot', 0.96, 'Vegan'),
('Brigadeiro', 1.58, 'Vegetarian'),
('Cinnamon', 9.42, 'Vegan'),
('Salted Caramel', 2.54, 'Vegetarian'),
('Onion', 0.45, 'Vegan'),
('Caramelized Onion', 0.93, 'Vegan'),
('Red Onion', 0.80, 'Vegan'),
('Spring Onion', 17.00, 'Vegan'),
('Carrot', 0.60, 'Vegan'),
('Chia', 4.39, 'Vegan'),
('Sweet Potato Chips', 11.27, 'Vegan'),
('Cocoa Powder', 6.88, 'Vegan'),
('Coconut Flakes', 9.66, 'Vegan'),
('Cilantro', 6.49, 'Vegan'),
('White Mushrooms', 3.55, 'Vegan'),
('Strawberry Jam', 12.98, 'Vegan'),
('Tomato Concentrate', 6.00, 'Vegan'),
('Zucchini', 3.62, 'Vegan'),
('Coconut Cream', 4.78, 'Vegan'),
('Creme Fraiche', 5.44, 'Vegetarian'),
('Dulce de Leche', 8.00, 'Vegetarian'),
('Aspargus', 8.32, 'Vegan'),
('Spinach', 4.45, 'Vegan'),
('Coconut Foam', 5.05, 'Vegan'),
('Vanilla Extract', 19.50, 'Vegan'),
('Flour', 0.46, 'Vegan'),
('Rice Flour', 2.00, 'Vegan'),
('Yeast', 7.31, 'Vegetarian' ),
('Oat Flakes', 1.68, 'Vegan'),
('Raspberry', 16.00, 'Vegan'),
('Chicken', 7.16, 'Omnivorous'),
('Ginger', 5.28, 'Vegan'),
('Fresh Ginger', 5.28, 'Vegan'),
('Granola', 8.68, 'Vegan'),
('Chickpeas', 1.17, 'Vegan'),
('Guacamole', 5.88, 'Vegan'),
('Mint', 7.55, 'Vegan'),
('Mint Leaves', 7.55, 'Vegan'),
('Hummus', 2.15, 'Vegan'),
('Beetroot Hummus', 1.96, 'Vegan'),
('Greek Yogurt', 2.01, 'Vegetarian'),
('Kiwi', 2.40, 'Vegan'),
('Orange', 0.71, 'Vegan'),
('Milk', 0.61, 'Vegetarian'),
('Condensed Milk', 2.77, 'Vegetarian'),
('Oat Milk', 1.64, 'Vegan'),
('Coconut Milk', 1.86, 'Vegan'),
('Soy Milk', 1.16, 'Vegan'),
('French Toast Milk', 0.93, 'Vegetarian'),
('Whole Milk', 0.61, 'Vegetarian'),
('Semi-Skimmed Milk', 0.61, 'Vegetarian'),
('Lime', 2.40, 'Vegan'),
('Lemon', 0.67, 'Vegan'),
('Green Apple', 1.60, 'Vegan'),
('Red Apple', 1.44, 'Vegan'),
('Mayonnaise', 2.08, 'Vegetarian'),
('Lemon Mayonnaise', 2.43, 'Vegetarian'),
('Mango', 4.36, 'Vegan'),
('Basil', 17.00, 'Vegan'),
('Butter', 7.05, 'Vegetarian'),
('Mascarpone', 6.67, 'Vegetarian'),
('Pasta', 1.48, 'Vegetarian'),
('Honey', 5.40, 'Vegetarian'),
('Cantaloupe Melon', 2.40, 'Vegan'),
('Blueberry', 24.24, 'Vegan'),
('Mixed Nuts', 10.85, 'Vegan'),
('Caramelized Mixed Nuts', 5.99, 'Vegan'),
('Hollandaise Sauce', 6.73, 'Vegetarian'),
('Worcestershire Sauce', 1.88, 'Vegetarian'),
('Mornay Sauce', 6.28, 'Vegetarian'),
('Tzatziki Sauce', 2.60, 'Vegetarian'),
('Strawberry', 6.54, 'Vegan'),
('Cream', 2.00, 'Vegetarian'),
('Nutmeg', 37.30, 'Vegan'),
('Walnuts', 12.46, 'Vegan'),
('Nutella', 8.08, 'Vegetarian'),
('Oil', 1.75, 'Vegan'),
('Eggs', 0.12, 'Vegetarian'),
('Chocolate Bagel Bread', 7.00, 'Vegetarian'),
('Bolo do Caco Bread', 5.50, 'Vegetarian'),
('Brioche Bread', 3.00, 'Vegetarian'),
('Curry Bread', 6.25, 'Vegetarian'),
('Tomato Bread', 5.34, 'Vegetarian'),
('Saloia Bread', 2.00, 'Vegetarian'),
('Chicken Breast', 7.16, 'Omnivorous'),
('Cucumber', 2.08, 'Vegan'),
('Pear', 0.80, 'Vegan'),
('Chili Pepper', 5.34, 'Vegan'),
('Black Pepper', 18.97, 'Vegan'),
('Red Bell Pepper', 2.08, 'Vegan'),
('Pistachio', 25.33, 'Vegan'),
('Mango Puree', 8.15, 'Vegan'),
('Emmental Cheese', 6.73, 'Vegetarian'),
('Feta Cheese', 8.47, 'Vegetarian'),
('Parmesan Cheese', 19.09, 'Vegetarian'),
('Sao Jorge Cheese', 1.18, 'Vegetarian'),
('Quinoa', 7.34, 'Vegan'),
('Radish', 2.40, 'Vegan'),
('Arugula', 9.16, 'Vegan'),
('Salt', 0.62, 'Vegan'),
('Iberian Salad', 7.92, 'Vegan'),
('Salmon', 17.72, 'Omnivorous'),
('Smoked Salmon', 17.72, 'Omnivorous'),
('Parsley', 5.10, 'Vegan'),
('Sesame Seeds', 7.14, 'Vegan'),
('Tahini', 14.64, 'Vegan'),
('Tomato', 1.60, 'Vegan'),
('Cherry Tomato', 3.08, 'Vegan'),
('Thyme', 14.75, 'Vegan'),
('Grape', 5.08, 'Vegan'),
('Vinegar', 0.54, 'Vegetarian'),
('Orange Vinaigrette', 1.80, 'Vegan'),
('White Wine', 1.42, 'Vegetarian'),
('Gin', 21.76, 'Vegetarian'),
('Tonic Water', 2.61, 'Vegan'),
('Sparkling Wine', 3.74, 'Vegetarian'),
('Frozen Mixed Berries', 3.33, 'Vegan'),
('Cachaça', 12.77, 'Vegetarian'),
('Goji Berries', 13.50, 'Vegan'),
('Pumpkin Seeds', 6.04, 'Vegan'),
('Sunflower Seeds', 2.47, 'Vegan'),
('Puffed Rice', 10.60, 'Vegan'),
('Cranberry', 10.12, 'Vegan');

SELECT COUNT(*) as "Total Ingredients" FROM dev_dba.ingredients;
