{
 "title": "Brunchio Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporters Health Check",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum by (job)(up)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "DB Reachability",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "PostgreSQL" }
   ]
  },
  { "title": "UI Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(api_gateway_http_request_duration_seconds_count{status_code=~\"2..|3..\"}[1m]))",
     "legendFormat": "Success Requests"
    },
    {
     "expr": "sum(rate(api_gateway_http_request_duration_seconds_count{status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "Failed Requests"
    }
   ]
  },
  {
   "title": "Satus Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  increase(api_gateway_http_request_duration_seconds_count[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(api_gateway_http_request_duration_seconds_sum[1m]))\n/\nsum by (method, route) (rate(api_gateway_http_request_duration_seconds_count[1m]))\n",
     "legendFormat": "{{method}} -> {{route}}"
    }
   ]
  }
 ]
}