apiVersion: 1

policies:
  - orgId: 1
    receiver: email-alerts
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: email-alerts
        object_matchers:
          - - service
            - =
            - api-gateway