filebeat.inputs:
  - type: filestream
    id: docker-containers
    paths:
      - ${GOINFRE_PATH}/*/*.log
    parsers:
      - container: ~

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]

queue.mem:
  events: 4096

logging.level: warning
logging.to_stderr: true